--- 
- hosts: 172.31.20.205
  become: yes
  tasks: 
  - name: install apache2
    apt: 
     name: apache2 
     state: present 

  - name: copy dynamic data 
    template:
      src: index.j2
      dest: /var/www/html/index.html
      
