--- 
- hosts: 172.31.31.77
  become: yes
  tasks: 
  - include_tasks: myfiles.yml

  - name: create a folder
    file:
     path: /home/ubuntu/myfolder 
     state: directory

  - name: i want to copy files
    copy:
     src: mystackfile 
     dest: /home/ubuntu/mystackfile.txt

  - name: install apache2
    apt:
     name: apache2 
     state: present 
    
  - name: download internet file
    get_url:
     url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes 