--- 
- hosts: 172.31.31.22 
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to create a folder
    file:
     path: /home/ubuntu/prince
     state: directory 

  - name: i want to copy file 
    copy:
     src: mystaticfile 
     dest: /home/ubuntu/mystaticfile.txt 

  - name: install apache2
    apt: 
     name: apache2
     state: present 