--- 
- hosts: 172.31.31.22 
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to create a folder
    file:
     path: /home/ubuntu/prince
     state: directory 

  - name: i want to copy file 
    copy:
     src: mystaticfile 
     dest: /home/ubuntu/mystaticfile.txt 

  - name: install apache2
    apt: 
     name: apache2
     state: present 

  - name: copy dynamic file
    template:
      src: index.j2
      dest: /var/www/html/index.html 

  - name: download internet file 
    get_url:
      url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
    
    