--- 
- hosts: 172.31.31.77
  become: yes
  tasks: 
  - name: install apache2
    apt:
     name: apache2
     state: present
    tags: myapache2

  - name: install git 
    apt: 
     name: git
     state: present
    tags: mygit 

  - name: install tree 
    apt: 
     name: tree
     state: present
    tags: mytree 