---
# tasks file for mytomcatrole


- include_tasks: myusers.yml
- include_tasks: installjava.yml
- include_tasks: download.yml
- include_tasks: permission.yml
- include_tasks: dasboard.yml
- include_tasks: starttomcat.yml